name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Discord
        run: |
          curl -i -H "Accept: application/json" \
          -H "Content-Type:application/json" \
          -X POST \
          --data "{\"content\": null,\"embeds\": [{\"title\": \"${{ github.repository }}$ Build Complete\",      \"description\": \"Commit: ${{ github.sha }}\\n[Build Artifacts](https://github.com/${{ github.repository }}$/actions/runs/${{ github.run_id }}#artifacts)\",      \"color\": 9371903,      \"author\": {        \"name\": \"Github Builds\"      }    }  ]}" \
          https://discord.com/api/webhooks/${{ secrets.WEBHOOK_ID }}/${{ secrets.WEBHOOK_TOKEN }}
